import { BranchPreset } from '../types';

export const BRANCH_PRESETS: BranchPreset[] = [
  {
    id: 'jee',
    name: 'JEE (Main & Advanced)',
    code: 'JEE',
    description: 'Complete physics, chemistry, and mathematics syllabus for engineering entrance.',
    subjects: [
      {
        name: 'Mathematics',
        code: 'JEE-MATH',
        teacher: 'Math Dept',
        totalLectures: 120,
        category: 'math',
        color: '#A78BFA',
      },
      {
        name: 'Physics',
        code: 'JEE-PHY',
        teacher: 'Physics Dept',
        totalLectures: 120,
        category: 'core',
        color: '#38BDF8',
      },
      {
        name: 'Physical Chemistry',
        code: 'JEE-PC',
        teacher: 'Chemistry Dept',
        totalLectures: 50,
        category: 'core',
        color: '#F472B6',
      },
      {
        name: 'Organic Chemistry',
        code: 'JEE-OC',
        teacher: 'Chemistry Dept',
        totalLectures: 60,
        category: 'core',
        color: '#34D399',
      },
      {
        name: 'Inorganic Chemistry',
        code: 'JEE-IOC',
        teacher: 'Chemistry Dept',
        totalLectures: 50,
        category: 'core',
        color: '#F59E0B',
      },
    ],
  },
  {
    id: 'neet',
    name: 'NEET (Medical)',
    code: 'NEET',
    description: 'Complete biology, physics, and chemistry syllabus for medical entrance.',
    subjects: [
      {
        name: 'Botany',
        code: 'NEET-BOT',
        teacher: 'Biology Dept',
        totalLectures: 90,
        category: 'core',
        color: '#34D399',
      },
      {
        name: 'Zoology',
        code: 'NEET-ZOO',
        teacher: 'Biology Dept',
        totalLectures: 90,
        category: 'core',
        color: '#10B981',
      },
      {
        name: 'Physics',
        code: 'NEET-PHY',
        teacher: 'Physics Dept',
        totalLectures: 120,
        category: 'core',
        color: '#38BDF8',
      },
      {
        name: 'Physical Chemistry',
        code: 'NEET-PC',
        teacher: 'Chemistry Dept',
        totalLectures: 50,
        category: 'core',
        color: '#F472B6',
      },
      {
        name: 'Organic Chemistry',
        code: 'NEET-OC',
        teacher: 'Chemistry Dept',
        totalLectures: 50,
        category: 'core',
        color: '#A78BFA',
      },
      {
        name: 'Inorganic Chemistry',
        code: 'NEET-IOC',
        teacher: 'Chemistry Dept',
        totalLectures: 50,
        category: 'core',
        color: '#F59E0B',
      },
    ],
  },
  {
    id: 'college',
    name: 'College Semester',
    code: 'BTECH',
    description: 'A standard college semester template (customize subjects later).',
    subjects: [
      {
        name: 'Core Subject 1',
        code: 'CORE-1',
        teacher: 'Prof 1',
        totalLectures: 40,
        category: 'core',
        color: '#38BDF8',
      },
      {
        name: 'Core Subject 2',
        code: 'CORE-2',
        teacher: 'Prof 2',
        totalLectures: 40,
        category: 'core',
        color: '#F472B6',
      },
      {
        name: 'Core Subject 3',
        code: 'CORE-3',
        teacher: 'Prof 3',
        totalLectures: 40,
        category: 'core',
        color: '#34D399',
      },
      {
        name: 'Mathematics/Stats',
        code: 'MATH',
        teacher: 'Math Dept',
        totalLectures: 40,
        category: 'math',
        color: '#A78BFA',
      },
      {
        name: 'Elective / Lab',
        code: 'ELEC',
        teacher: 'Dept',
        totalLectures: 30,
        category: 'elective',
        color: '#F59E0B',
      },
    ],
  },
];